# Generated by Django 5.1.3 on 2024-11-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_m_qr_image_user_delete_m_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_qr_image',
            name='color_qr',
            field=models.TextField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='m_qr_image',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
