# Generated by Django 5.1.3 on 2024-11-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_m_qr_image_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_qr_image',
            name='color_qr',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
