# Generated by Django 5.1.3 on 2024-11-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_m_qr_image_color_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_qr_image',
            name='logo_url',
            field=models.ImageField(blank=True, default='images/img-not-found.png', null=True, upload_to='images/'),
        ),
    ]
